### ISSUE TITLE
Python3 UnicodeDecodeError

### ISSUE THREAD

**Issue by ulidtko** [msoulier/tftpy#109]
```
[2020-06-26 00:26:24,329] Sending tftp upload request to 192.168.1.1
[2020-06-26 00:26:24,329]     filename -> squashfs.chk
[2020-06-26 00:26:24,329]     options -> {}
[2020-06-26 00:26:24,329] Received ACK from server
Traceback (most recent call last):
  File "/usr/bin/tftpy_client", line 136, in <module>
    main()
  File "/usr/bin/tftpy_client", line 126, in main
    tclient.upload(options.upload,
  File "/usr/lib/python3.8/site-packages/tftpy/TftpClient.py", line 93, in upload
    self.context.start()
  File "/usr/lib/python3.8/site-packages/tftpy/TftpContexts.py", line 319, in start
    self.cycle()
  File "/usr/lib/python3.8/site-packages/tftpy/TftpContexts.py", line 202, in cycle
    self.state = self.state.handle(recvpkt, raddress, rport)
  File "/usr/lib/python3.8/site-packages/tftpy/TftpStates.py", line 527, in handle
    self.context.pending_complete = self.sendDAT()
  File "/usr/lib/python3.8/site-packages/tftpy/TftpStates.py", line 95, in sendDAT
    buffer = self.context.fileobj.read(blksize)
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 4: invalid start byte
```

**Comment by wlq6037** [comment]
hi,@ulidtko can you post more details about it? besides,you can add '-d' option in client side that will catch some useful information.

**Comment by ulidtko** [comment]
@wlq6037 hi, in this line, `TftpStates.py:95`:

        buffer = self.context.fileobj.read(blksize)

— the `fileobj` is incorrect type, it's a "text-mode" stream — while it should be "binary-mode" stream.

For example, on files, you can open files in 2 ways: text and binary. Calling `.read()` on text file will return `str` (unicode strings), calling `.read()` on binary file will return `bytes` (raw undecoded bytes).

```
>>> open('/dev/null', 'r')
<_io.TextIOWrapper name='/dev/null' mode='r' encoding='UTF-8'>
>>> 
>>> open('/dev/null', 'rb')
<_io.BufferedReader name='/dev/null'>
```

```
>>> open('/dev/null', 'r').read()
''
>>> open('/dev/null', 'rb').read()
b''
```

The error happens (I guess) because the code is trying to interpret network data from the socket as UTF8-encoded text, which of course it isn't, and leads to the error. It should use raw `bytes`, without trying to decode those to text.

**Comment by wlq6037** [comment]
@ulidtko  yep,u trance the bug and hit the spot :blush: will u fix it ?

**Comment by ulidtko** [comment]
@wlq6037 no sorry; this was months ago and I no longer have an easy way to reproduce this.  Back then I needed a TFTP client to debrick a device (reflash firmware). It failed like I reported.

Maybe this is easy to reproduce with tests?

This kind of bug is a frequent result of Python 2 → 3 migration. I guess, perhaps tftpy wasn't tested enough under Python 3.

**Comment by ulidtko** [comment]
I can easily check that some of the important logic in TftpStates is not covered by tests.

```
ulidtko@pasocon /t/tftpy (master)> coverage report
Name                         Stmts   Miss  Cover
------------------------------------------------
tftpy/TftpClient.py             50      3    94%
tftpy/TftpContexts.py          233     27    88%
tftpy/TftpPacketFactory.py      19      0   100%
tftpy/TftpPacketTypes.py       287     28    90%
tftpy/TftpServer.py            150     39    74%
tftpy/TftpShared.py             28      1    96%
tftpy/TftpStates.py            349    151    57%
tftpy/__init__.py               12      1    92%
------------------------------------------------
TOTAL                         1128    250    78%
```

Like here for example, this whole class is not exercized by `t/tests.py`:
![image](https://user-images.githubusercontent.com/365338/108199994-7759c580-7126-11eb-9e04-9f2d1daaf00e.png)

(Red highlight means that those lines were never executed by the unittests; see [coverage guide](https://coverage.readthedocs.io))

**Comment by ulidtko** [comment]
OK I found the problem. Here:

https://github.com/msoulier/tftpy/blob/007d5d720681d1b7f46baf23c1d272be1dd38574/tftpy/TftpContexts.py#L283-L286

`sys.stdin` is a text stream.

----------

So, here's the repro recipe:

```
> tftpy_client -H localhost -u README -i- < README
[2021-02-17 14:10:46,623] Sending tftp upload request to localhost
[2021-02-17 14:10:46,624]     filename -> README
[2021-02-17 14:10:46,624]     options -> {}
[2021-02-17 14:10:46,626] Received ACK from server
[2021-02-17 14:10:46,627] Transferred 512 bytes
[2021-02-17 14:10:46,627] Transferred 1024 bytes
Traceback (most recent call last):
  File "/usr/bin/tftpy_client", line 136, in <module>
    main()
  File "/usr/bin/tftpy_client", line 126, in main
    tclient.upload(options.upload,
  File "/usr/lib/python3.9/site-packages/tftpy/TftpClient.py", line 93, in upload
    self.context.start()
  File "/usr/lib/python3.9/site-packages/tftpy/TftpContexts.py", line 319, in start
    self.cycle()
  File "/usr/lib/python3.9/site-packages/tftpy/TftpContexts.py", line 202, in cycle
    self.state = self.state.handle(recvpkt, raddress, rport)
  File "/usr/lib/python3.9/site-packages/tftpy/TftpStates.py", line 452, in handle
    self.context.pending_complete = self.sendDAT()
  File "/usr/lib/python3.9/site-packages/tftpy/TftpStates.py", line 106, in sendDAT
    self.context.sock.sendto(dat.encode().buffer,
  File "/usr/lib/python3.9/site-packages/tftpy/TftpPacketTypes.py", line 299, in encode
    data = self.data.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\u0144' in position 360: ordinal not in range(128)
```

Tftpy's README is enough to trigger, thanks to U+0144 character on line 45:
https://github.com/msoulier/tftpy/blob/007d5d720681d1b7f46baf23c1d272be1dd38574/README#L45

The stacktrace is different than in OP, because the `README` is valid UTF-8 while the one in OP isn't (and so fails slightly earlier).

The `-i-` is what triggers `sys.stdin` usage — which is a text stream and does de/re-coding from/to bytes. `tftpy_client -H localhost -u README` works OK.

I'll send a patch in a minute.

**Comment by msoulier** [comment]
On 17/02/21 Maxim Ivanov said:

> OK I found the problem. Here:
> 
> https://github.com/msoulier/tftpy/blob/007d5d720681d1b7f46baf23c1d272be1dd38574/tftpy/TftpContexts.py#L283-L286
> 
> `sys.stdin` is a text stream.

Feel free to add a test case to cover this.

**Comment by ulidtko** [comment]
@msoulier indeed, the line with the bug is not covered.

![image](https://user-images.githubusercontent.com/365338/108225857-ffe75e80-7144-11eb-9f3c-f1cc325fc1ad.png)

However, [some people suggest][•]:

> If you have to monkey patch sys.stdin, there is a high possibility you are trying to "unit test" too much.

— and I tend to agree in this case; simply from a cost/benefit perspective. The bug highly depends on system environment (which OS & which Python version), scripting the necessary setup seems like overkill just to cover 1 line — meanwhile, the "manual test" is 1-line command + a file with some unicode, I'm perfectly happy to not automate that.

[•]: https://stackoverflow.com/questions/6271947/how-can-i-simulate-input-to-stdin-for-pyunit
