### ISSUE TITLE
Python 3 compatibility issue when writing to stdout

### ISSUE THREAD

**Issue by kazkansouh** [msoulier/tftpy#113]
Hello,

I was just using this library and noticed when dumping to stdout by using the "-" option there is the following error:
```
[2020-09-11 08:16:42,305]     options -> {}                                                                                                                                            
[2020-09-11 08:16:42,317] Transferred 31 bytes                                                                                                                                         
[2020-09-11 08:16:42,318] Set remote port for session to 1136                                                                                                                          
[2020-09-11 08:16:42,318] Received DAT from server                                                                                                                                     
[2020-09-11 08:16:42,318] Handling DAT packet - block 1                    
[2020-09-11 08:16:42,318] Sending ack to block 1                                                                                                                                       
Traceback (most recent call last):        
  File "/root/.local/bin/tftpy_client.py", line 136, in <module>
    main()                                                                                                                                                                             
  File "/root/.local/bin/tftpy_client.py", line 120, in main 
    tclient.download(options.download,                                                     
  File "/root/.local/lib/python3.8/site-packages/tftpy/TftpClient.py", line 58, in download
    self.context.start()                                                                   
  File "/root/.local/lib/python3.8/site-packages/tftpy/TftpContexts.py", line 402, in start
    self.cycle()                                                                           
  File "/root/.local/lib/python3.8/site-packages/tftpy/TftpContexts.py", line 202, in cycle
    self.state = self.state.handle(recvpkt, raddress, rport)
  File "/root/.local/lib/python3.8/site-packages/tftpy/TftpStates.py", line 586, in handle                               
    return self.handleDat(pkt)                                                             
  File "/root/.local/lib/python3.8/site-packages/tftpy/TftpStates.py", line 182, in handleDat
    self.context.fileobj.write(pkt.data)                                                   
TypeError: write() argument must be str, not bytes
```

It appears to be caused by the following line

https://github.com/msoulier/tftpy/blob/af2f2fe89a3bf45748b78703820efb0986a8207a/tftpy/TftpContexts.py#L367

Probably it should be updated to:
```python
self.fileobj = sys.stdout.buffer
```

I suspect the same issue applies to the input:

https://github.com/msoulier/tftpy/blob/af2f2fe89a3bf45748b78703820efb0986a8207a/tftpy/TftpContexts.py#L284

i.e. it should be updated to:
```python
self.fileobj = sys.stdin.buffer
```

If you like, I can submit a PR to fix this?

**Comment by msoulier** [comment]
Need a testcase to cover this.

**Comment by msoulier** [comment]
Added a stdout.py to reproduce this. Easily done.

**Comment by msoulier** [comment]
Test looks good with the proposed fix. 
```
OK
input_path is /home/msoulier/work/tftpy/tests/640KBFILE
DEBUG [tftpy.TftpContext:271] TftpContextServer.__del__
DEBUG [tftpy.TftpContext:133] TftpContext.__del__
DEBUG [tftpy.TftpContext:56] TftpMetrics.__del__
DEBUG [tftpy.TftpContext:271] TftpContextServer.__del__
DEBUG [tftpy.TftpContext:133] TftpContext.__del__
DEBUG [tftpy.TftpContext:56] TftpMetrics.__del__
DEBUG [tftpy.TftpContext:271] TftpContextServer.__del__
DEBUG [tftpy.TftpContext:133] TftpContext.__del__
DEBUG [tftpy.TftpContext:56] TftpMetrics.__del__
PYTHONIOENCODING=UTF-8 PYTHONPATH=. /usr/bin/env python3 tests/stdout.py > /tmp/out
```
